# Generated by Django 3.2.16 on 2022-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField()),
            ],
        ),
    ]
